import React from 'react';
import {
  Heading,
  AlignLeft,
  Image as ImageIcon,
  LayoutGrid,
  FileText,
  Table as TableIcon,
  HelpCircle,
  Link2,
  Columns as ColumnsIcon,
  Video,
  MapPin,
  Minus,
  Newspaper,
  Users,
  GraduationCap,
  Award,
  Sparkles,
  PlaySquare,
  Quote as QuoteIcon,
  AlertTriangle,
  Clock,
  Calendar,
  Share2,
  FolderTree,
  Sliders,
} from 'lucide-react';
import { PageBlockType } from '@college/shared';

export type PaletteCategory = 'layout' | 'hero' | 'content' | 'academic' | 'nav';

export interface PaletteBlockDef {
  type: PageBlockType;
  icon: React.ComponentType<{ className?: string }>;
  nameUz: string;
  nameRu: string;
  descUz: string;
  descRu: string;
  category: PaletteCategory;
  defaultConfig: unknown;
}

export const PALETTE_CATEGORIES: { id: PaletteCategory; nameUz: string; nameRu: string }[] = [
  { id: 'layout', nameUz: 'Tuzilma va konteynerlar', nameRu: 'Макет и контейнеры' },
  { id: 'hero', nameUz: 'Bosh ekran va bannerlar', nameRu: 'Главные экраны и призывы' },
  { id: 'content', nameUz: 'Matn va media', nameRu: 'Текст и медиа' },
  { id: 'academic', nameUz: 'Akademik va dinamik maʼlumotlar', nameRu: 'Данные и виджеты' },
  { id: 'nav', nameUz: 'Navigatsiya va xizmatlar', nameRu: 'Навигация и утилиты' },
];

export const PALETTE_BLOCKS: PaletteBlockDef[] = [
  // ---------------------------------------------------------------------------
  // 1. Tuzilma va konteynerlar (Layout & Containers)
  // ---------------------------------------------------------------------------
  {
    type: 'cards_grid',
    icon: LayoutGrid,
    nameUz: 'Kartochkalar toʻplami',
    nameRu: 'Сетка карточек',
    descUz: '2-4 ta interaktiv kartochkalar: nishon, matn va havola',
    descRu: 'Адаптивные карточки с иконками, бейджами и ссылками',
    category: 'layout',
    defaultConfig: {
      titleUz: 'Asosiy yoʻnalishlar',
      titleRu: 'Ключевые направления',
      columns: 3,
      cards: [
        {
          id: 'card-1',
          titleUz: 'Dasturiy injiniring',
          titleRu: 'Программная инженерия',
          descriptionUz: 'Zamonaviy veb va mobil ilovalarni ishlab chiqish',
          descriptionRu: 'Разработка современных веб и мобильных приложений',
          badgeUz: 'IT',
          badgeRu: 'IT',
          linkUrl: '/specialties',
        },
        {
          id: 'card-2',
          titleUz: 'Avtomobillarga texnik xizmat',
          titleRu: 'Техобслуживание авто',
          descriptionUz: 'Diagnostika va elektronika tizimlarini taʼmirlash',
          descriptionRu: 'Диагностика и ремонт электронных систем',
          badgeUz: 'Texnika',
          badgeRu: 'Техника',
          linkUrl: '/specialties',
        },
        {
          id: 'card-3',
          titleUz: 'Buxgalteriya va audit',
          titleRu: 'Бухучет и аудит',
          descriptionUz: 'Moliyaviy hisobot va 1C dasturlari',
          descriptionRu: 'Финансовая отчетность и системы 1С',
          badgeUz: 'Moliya',
          badgeRu: 'Финансы',
          linkUrl: '/specialties',
        },
      ],
    },
  },
  {
    type: 'tabs',
    icon: Sliders,
    nameUz: 'Vkladkalar (Tabs)',
    nameRu: 'Вкладки (Табы)',
    descUz: 'Klaviatura bilan boshqariladigan mazmunli vkladkalar (ARIA)',
    descRu: 'Переключаемые вкладки с поддержкой стрелок клавиатуры',
    category: 'layout',
    defaultConfig: {
      titleUz: 'Taʼlim shakllari',
      titleRu: 'Формы обучения',
      defaultActiveIndex: 0,
      items: [
        {
          id: 'tab-1',
          labelUz: '9-sinf negizida',
          labelRu: 'На базе 9 классов',
          contentUzHtml: '<p>Davlat granti asosida 3 yillik toʻliq oʻrta professional taʼlim.</p>',
          contentRuHtml: '<p>3 года обучения на основе государственного гранта.</p>',
        },
        {
          id: 'tab-2',
          labelUz: '11-sinf negizida',
          labelRu: 'На базе 11 классов',
          contentUzHtml: '<p>2 yillik intensiv kasbiy taʼlim va dual taʼlim shakli.</p>',
          contentRuHtml: '<p>2 года обучения, дневная и дуальная формы подготовки.</p>',
        },
      ],
    },
  },
  {
    type: 'accordion',
    icon: HelpCircle,
    nameUz: 'Akkordeon (Savol-javob)',
    nameRu: 'Аккордеон (FAQ)',
    descUz: 'Ochilib-yopiluvchi savol-javoblar va yoʻriqnomalar bloki',
    descRu: 'Раскрывающийся список для FAQ и справочной информации',
    category: 'layout',
    defaultConfig: {
      titleUz: 'Koʻp beriladigan savollar',
      titleRu: 'Часто задаваемые вопросы',
      allowMultiple: true,
      items: [
        {
          id: 'faq-1',
          questionUz: 'Hujjatlar qachongacha qabul qilinadi?',
          questionRu: 'До какого числа принимаются документы?',
          answerUzHtml: '<p>Arizalar 2026-yil 15-avgustga qadar my.edu.uz orqali qabul qilinadi.</p>',
          answerRuHtml: '<p>Заявления принимаются до 15 августа 2026 года через my.edu.uz.</p>',
        },
      ],
    },
  },
  {
    type: 'columns',
    icon: ColumnsIcon,
    nameUz: 'Ustunlar (2-3 ustun)',
    nameRu: 'Колонки (2-3 колонки)',
    descUz: 'Yonma-yon joylashgan 2 yoki 3 ta matnli va rasmli ustun',
    descRu: 'Простая раскладка из 2 или 3 колонок с текстом',
    category: 'layout',
    defaultConfig: {
      columns: 2,
      items: [
        {
          id: 'col-1',
          titleUz: '1-yoʻnalish',
          titleRu: 'Направление 1',
          contentUzHtml: '<p>Birinchi ustun matni</p>',
          contentRuHtml: '<p>Текст первой колонки</p>',
        },
        {
          id: 'col-2',
          titleUz: '2-yoʻnalish',
          titleRu: 'Направление 2',
          contentUzHtml: '<p>Ikkinchi ustun matni</p>',
          contentRuHtml: '<p>Текст второй колонки</p>',
        },
      ],
    },
  },

  // ---------------------------------------------------------------------------
  // 2. Bosh ekran va bannerlar (Hero & Banners)
  // ---------------------------------------------------------------------------
  {
    type: 'hero',
    icon: Sparkles,
    nameUz: 'Hero (Bosh ekran)',
    nameRu: 'Hero-экран',
    descUz: 'Akademik asosiy sarlavha, tugmalar va rasmli katta blok',
    descRu: 'Главный экран страницы с заголовком, кнопками и фото',
    category: 'hero',
    defaultConfig: {
      badgeUz: 'Davlat taʼlim muassasasi',
      badgeRu: 'Государственное учреждение',
      titleUz: 'Zamonaviy kasblarni biz bilan egallang',
      titleRu: 'Освойте современные профессии вместе с нами',
      subtitleUz: 'Xalqaro andozalarga mos amaliy ustaxonalar va kafolatlangan taʼlim',
      subtitleRu: 'Мастерские международных стандартов и качественное обучение',
      primaryActionTextUz: 'Yoʻnalishlar',
      primaryActionTextRu: 'Специальности',
      primaryActionUrl: '/specialties',
      align: 'left',
      backgroundVariant: 'none',
    },
  },
  {
    type: 'banner_alert',
    icon: AlertTriangle,
    nameUz: 'Eʼlon / Ogohlantirish',
    nameRu: 'Баннер-уведомление',
    descUz: 'Muhim rasmiy bildirishnoma yoki muddatlar haqida xabar',
    descRu: 'Информационная плашка для срочных объявлений и дедлайнов',
    category: 'hero',
    defaultConfig: {
      variant: 'info',
      titleUz: 'Qabul komissiyasi eʼloni',
      titleRu: 'Объявление приемной комиссии',
      messageUz: 'Hujjatlar qabuli my.edu.uz portali orqali boshlandi.',
      messageRu: 'Прием документов стартовал на портале my.edu.uz.',
      actionTextUz: 'Arizani yuborish',
      actionTextRu: 'Подать заявление',
      actionUrl: 'https://my.edu.uz',
      isDismissible: false,
    },
  },
  {
    type: 'call_to_action',
    icon: Award,
    nameUz: 'Chaqiruv bloki (CTA)',
    nameRu: 'Призыв к действию (CTA)',
    descUz: 'Hujjat topshirish yoki bogʻlanishga undovchi maxsus karta',
    descRu: 'Конверсионный блок для подачи заявки или записи',
    category: 'hero',
    defaultConfig: {
      titleUz: 'Savollaringiz bormi? Mutaxassislarimiz javob beradi',
      titleRu: 'Остались вопросы? Наши консультанты помогут',
      descriptionUz: 'Qabul shartlari va yoʻnalish tanlash boʻyicha bepul maslahat oling.',
      descriptionRu: 'Получите бесплатную консультацию по выбору профессии и поступлению.',
      primaryButtonTextUz: 'Qoʻngʻiroq qilish',
      primaryButtonTextRu: 'Позвонить',
      primaryButtonUrl: 'tel:+998732440000',
    },
  },
  {
    type: 'quote',
    icon: QuoteIcon,
    nameUz: 'Iqtibos (Quote)',
    nameRu: 'Цитата руководителя',
    descUz: 'Rahbar yoki olimning fotosurati va lavozimi bilan iqtibos',
    descRu: 'Академическая цитата с портретом и регалиями автора',
    category: 'hero',
    defaultConfig: {
      quoteTextUz: 'Taʼlim va amaliyot uygʻunligi — yuqori malakali mutaxassis tayyorlashning asosiy kalitidir.',
      quoteTextRu: 'Единство теории и практики — главный ключ к подготовке высококвалифицированных кадров.',
      authorUz: 'Direktor',
      authorRu: 'Директор',
      roleUz: 'Texnikum rahbari',
      roleRu: 'Руководитель техникума',
    },
  },

  // ---------------------------------------------------------------------------
  // 3. Matn va media (Content & Media)
  // ---------------------------------------------------------------------------
  {
    type: 'heading',
    icon: Heading,
    nameUz: 'Sarlavha (Heading)',
    nameRu: 'Заголовок (H1-H6)',
    descUz: 'Sahifaning semantik iyerarxik sarlavhasi (H1-H6)',
    descRu: 'Семантический заголовок H1-H6 для структуры страницы',
    category: 'content',
    defaultConfig: { level: 2, textUz: 'Yangi sarlavha', textRu: 'Новый заголовок', align: 'left' },
  },
  {
    type: 'rich_text',
    icon: AlignLeft,
    nameUz: 'Formatlangan matn',
    nameRu: 'Текстовый блок',
    descUz: 'Paragraflar, roʻyxatlar, havolalar va formatlangan matn',
    descRu: 'Параграфы, списки, ссылки и форматированный контент',
    category: 'content',
    defaultConfig: {
      contentUzHtml: '<p>Ushbu boʻlimga asosiy akademik va rasmiy axborot matnini kiriting.</p>',
      contentRuHtml: '<p>Введите основной текст раздела на русском языке.</p>',
      containerWidth: 'full',
    },
  },
  {
    type: 'image_text',
    icon: ImageIcon,
    nameUz: 'Rasm + Matn',
    nameRu: 'Фото + Текст сбоку',
    descUz: 'Surat va uning yonida matnli tavsif (chap/oʻng almashinadi)',
    descRu: 'Композиция из фотографии и описательного текста рядом',
    category: 'content',
    defaultConfig: {
      titleUz: 'Oʻquv amaliyot ustaxonalari',
      titleRu: 'Учебно-производственные мастерские',
      contentUzHtml: '<p>Texnikumimiz ustaxonalari Germaniya va Yaponiya dastgohlari bilan jihozlangan.</p>',
      contentRuHtml: '<p>Мастерские техникума оснащены современными станками международного класса.</p>',
      imageUrl: '/images/news/lab-opening.svg',
      imageAltUz: 'Ustaxona jihozlari',
      imageAltRu: 'Оборудование мастерских',
      imagePosition: 'right',
    },
  },
  {
    type: 'image_carousel',
    icon: PlaySquare,
    nameUz: 'Slayder (Karusel)',
    nameRu: 'Слайдер фотографий',
    descUz: 'WCAG 2.2.2 talabiga mos pauza tugmali fotosuratlar karuseli',
    descRu: 'Слайдер с обязательной кнопкой паузы по стандарту WCAG 2.2.2',
    category: 'content',
    defaultConfig: {
      titleUz: 'Texnikum hayotidan fotolavhalar',
      titleRu: 'Фотохроника техникума',
      hasPauseControl: true,
      autoAdvance: false,
      intervalSeconds: 5,
      slides: [
        {
          id: 'sl-1',
          imageUrl: '/images/news/champion-2026.svg',
          altTextUz: 'Musobaqa gʻoliblari',
          altTextRu: 'Победители соревнований',
          captionUz: 'WorldSkills chempionati gʻoliblari',
          captionRu: 'Призеры чемпионата WorldSkills',
        },
        {
          id: 'sl-2',
          imageUrl: '/images/news/lab-opening.svg',
          altTextUz: 'Yangi laboratoriya',
          altTextRu: 'Новая лаборатория',
          captionUz: 'Yangi IT-laboratoriya ochilishi',
          captionRu: 'Открытие IT-лаборатории',
        },
      ],
    },
  },
  {
    type: 'image',
    icon: ImageIcon,
    nameUz: 'Bitta fotosurat',
    nameRu: 'Изображение',
    descUz: 'Alt-matn va izohli alohida tasvir',
    descRu: 'Одиночное изображение с подписью и alt-текстом',
    category: 'content',
    defaultConfig: {
      url: '/images/news/champion-2026.svg',
      altTextUz: 'Texnikum binosi',
      altTextRu: 'Здание техникума',
      isDecorative: false,
      aspectRatio: '16:9',
    },
  },
  {
    type: 'gallery',
    icon: LayoutGrid,
    nameUz: 'Fotogalereya',
    nameRu: 'Фотогалерея',
    descUz: 'Kattalashtirib koʻrish imkoniyatiga ega fotolavhalar toʻplami',
    descRu: 'Сетка фотографий с полноэкранным просмотром',
    category: 'content',
    defaultConfig: {
      columns: 3,
      enableLightbox: true,
      items: [
        {
          id: 'gal-1',
          url: '/images/news/champion-2026.svg',
          altTextUz: 'Surat 1',
          altTextRu: 'Фото 1',
        },
        {
          id: 'gal-2',
          url: '/images/news/lab-opening.svg',
          altTextUz: 'Surat 2',
          altTextRu: 'Фото 2',
        },
      ],
    },
  },
  {
    type: 'table',
    icon: TableIcon,
    nameUz: 'Jadval',
    nameRu: 'Таблица данных',
    descUz: 'Sarlavha va qatorlarga ega ikki tilli akademik jadval',
    descRu: 'Таблица для квот, цен, нормативов и расписаний',
    category: 'content',
    defaultConfig: {
      headersUz: ['Kodi', 'Mutaxassislik nomi', 'Oʻqish muddati'],
      headersRu: ['Код', 'Наименование специальности', 'Срок обучения'],
      rowsUz: [
        ['40610101', 'Kompyuter injiniringi', '3 yil'],
        ['40710102', 'Avtomobil taʼmiri', '3 yil'],
      ],
      rowsRu: [
        ['40610101', 'Компьютерная инженерия', '3 года'],
        ['40710102', 'Авторемонт', '3 года'],
      ],
    },
  },
  {
    type: 'video_embed',
    icon: Video,
    nameUz: 'Video (YouTube / Mover)',
    nameRu: 'Видеоролик',
    descUz: 'Ruxsat etilgan videohostinglardan videolarni xavfsiz joylashtirish',
    descRu: 'Встраивание видео с YouTube, Vimeo или Mover.uz',
    category: 'content',
    defaultConfig: {
      url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      titleUz: 'Texnikum taqdimot videosi',
      titleRu: 'Презентационный ролик техникума',
      aspectRatio: '16:9',
    },
  },

  // ---------------------------------------------------------------------------
  // 4. Akademik va dinamik maʼlumotlar (Academic & Dynamic Data)
  // ---------------------------------------------------------------------------
  {
    type: 'stats_counter',
    icon: Award,
    nameUz: 'Statistika koʻrsatkichlari (KPI)',
    nameRu: 'Счетчики статистики (KPI)',
    descUz: 'Talabalar, pedagoglar, laboratoriyalar va foizlar raqamlarda',
    descRu: 'Ключевые цифровые показатели деятельности техникума',
    category: 'academic',
    defaultConfig: {
      titleUz: 'Texnikum raqamlarda',
      titleRu: 'Техникум в цифрах',
      columns: 4,
      stats: [
        { id: 's1', value: '1,200+', labelUz: 'Talabalar soni', labelRu: 'Студентов' },
        { id: 's2', value: '85+', labelUz: 'Malakali ustozlar', labelRu: 'Педагогов' },
        { id: 's3', value: '14 ta', labelUz: 'Oʻquv laboratoriyalari', labelRu: 'Лабораторий' },
        { id: 's4', value: '92%', labelUz: 'Bitiruvchilar bandligi', labelRu: 'Трудоустройство' },
      ],
    },
  },
  {
    type: 'timeline',
    icon: Clock,
    nameUz: 'Tarixiy лента (Timeline)',
    nameRu: 'Хронологическая лента',
    descUz: 'Texnikum rivojlanish bosqichlari yoki qabul jarayoni sanalari',
    descRu: 'Хроника ключевых событий, вех истории или этапов приема',
    category: 'academic',
    defaultConfig: {
      titleUz: 'Rivojlanish bosqichlari',
      titleRu: 'Этапы развития',
      items: [
        {
          id: 't-1',
          dateOrYear: '1978-yil',
          titleUz: 'Muassasa tashkil etildi',
          titleRu: 'Основание учреждения',
          descriptionUz: 'Mintaqaviy sanoat uchun mutaxassislar tayyorlash boshlandi.',
          descriptionRu: 'Начало подготовки специалистов для региональной промышленности.',
        },
        {
          id: 't-2',
          dateOrYear: '2024-yil',
          titleUz: 'Texnikum maqomi berildi',
          titleRu: 'Преобразование в техникум',
          descriptionUz: 'PF-158 Farmoni asosida oliy taʼlim bilan integratsiya qilindi.',
          descriptionRu: 'Интеграция с вузами на основании Указа Президента УП-158.',
        },
      ],
    },
  },
  {
    type: 'documents_list',
    icon: FileText,
    nameUz: 'Hujjatlar roʻyxati (Qidiruvli)',
    nameRu: 'Реестр документов (с поиском)',
    descUz: 'Qidiruv, toifalar va hajm koʻrsatilgan yuklab olinuvchi hujjatlar',
    descRu: 'Документы с поиском, категориями и размером файлов',
    category: 'academic',
    defaultConfig: {
      titleUz: 'Rasmiy hujjatlar va nizomlar',
      titleRu: 'Официальные документы и положения',
      enableSearch: true,
      documents: [
        {
          id: 'd-1',
          titleUz: 'Texnikum Ustavi (Tasdiqlangan)',
          titleRu: 'Устав техникума (Утвержденный)',
          documentNumber: '№ 14-B',
          issueDate: '2024-11-10',
          fileUrl: '/documents/sample-ustav.pdf',
          fileType: 'pdf',
          fileSizeBytes: 2450000,
        },
      ],
    },
  },
  {
    type: 'specialties_feed',
    icon: GraduationCap,
    nameUz: 'Yoʻnalishlar vidjeti',
    nameRu: 'Виджет направлений',
    descUz: 'Maʼlumotlar bazasidan jonli taʼlim yoʻnalishlari katalogi',
    descRu: 'Динамический каталог специальностей из базы данных',
    category: 'academic',
    defaultConfig: {
      titleUz: 'Taʼlim yoʻnalishlari',
      titleRu: 'Направления подготовки',
      limit: 6,
    },
  },
  {
    type: 'events_feed',
    icon: Calendar,
    nameUz: 'Tadbirlar lentasi',
    nameRu: 'Виджет мероприятий',
    descUz: 'Boʻlajak konferensiyalar, ochiq eshiklar kuni va tadbirlar',
    descRu: 'Лента предстоящих мероприятий, открытых дверей и событий',
    category: 'academic',
    defaultConfig: {
      titleUz: 'Kutilayotgan tadbirlar',
      titleRu: 'Предстоящие события',
      limit: 4,
      upcomingOnly: true,
    },
  },
  {
    type: 'latest_news_list',
    icon: Newspaper,
    nameUz: 'Yangiliklar lentasi',
    nameRu: 'Виджет новостей',
    descUz: 'Texnikumning soʻnggi rasmiy yangiliklari va maqolalari',
    descRu: 'Свежие новости и статьи из базы портала',
    category: 'academic',
    defaultConfig: {
      titleUz: 'Soʻnggi yangiliklar',
      titleRu: 'Последние новости',
      limit: 4,
      showCover: true,
    },
  },
  {
    type: 'staff_cards',
    icon: Users,
    nameUz: 'Pedagoglar kartochkalari',
    nameRu: 'Карточки педагогов',
    descUz: 'Oʻqituvchilar va ishlab chiqarish taʼlimi ustalari tarkibi',
    descRu: 'Каталог преподавателей и мастеров с фото и должностью',
    category: 'academic',
    defaultConfig: {
      titleUz: 'Pedagogik tarkib',
      titleRu: 'Педагогический состав',
      limit: 8,
      category: 'all',
    },
  },
  {
    type: 'schedule_widget',
    icon: Clock,
    nameUz: 'Dars jadvali vidjeti',
    nameRu: 'Виджет расписания',
    descUz: 'Oʻquv guruhlari boʻyicha kunlik darslar jadvali',
    descRu: 'Интерактивное расписание пар по группам и дням недели',
    category: 'academic',
    defaultConfig: {
      titleUz: 'Dars jadvali',
      titleRu: 'Расписание занятий',
      defaultGroupName: 'DASTUR-21',
    },
  },

  // ---------------------------------------------------------------------------
  // 5. Navigatsiya va xizmatlar (Navigation & Utilities)
  // ---------------------------------------------------------------------------
  {
    type: 'anchor_nav',
    icon: FolderTree,
    nameUz: 'Mundarija (TOC)',
    nameRu: 'Оглавление страницы',
    descUz: 'Sahifadagi H2/H3 sarlavhalaridan avtomatik hosil boʻluvchi mundarija',
    descRu: 'Автоматическое оглавление на основе H2/H3 заголовков',
    category: 'nav',
    defaultConfig: {
      titleUz: 'Sahifa mundarijasi',
      titleRu: 'Содержание страницы',
    },
  },
  {
    type: 'social_links',
    icon: Share2,
    nameUz: 'Ijtimoiy tarmoqlar',
    nameRu: 'Кнопки соцсетей',
    descUz: 'Telegram, YouTube, Facebook rasmiy kanallari tugmalari',
    descRu: 'Ссылки на официальные каналы учреждения в соцсетях',
    category: 'nav',
    defaultConfig: {
      titleUz: 'Biz ijtimoiy tarmoqlarda',
      titleRu: 'Мы в социальных сетях',
      links: [
        { id: 'tg', platform: 'telegram', titleUz: 'Telegram kanal', titleRu: 'Канал Telegram', url: 'https://t.me/texnikum2' },
        { id: 'yt', platform: 'youtube', titleUz: 'YouTube kanal', titleRu: 'Канал YouTube', url: 'https://youtube.com/@texnikum2' },
        { id: 'fb', platform: 'facebook', titleUz: 'Facebook sahifa', titleRu: 'Страница Facebook', url: 'https://facebook.com/texnikum2' },
      ],
    },
  },
  {
    type: 'map_embed',
    icon: MapPin,
    nameUz: 'Xarita (OpenStreetMap)',
    nameRu: 'Карта OpenStreetMap',
    descUz: 'Oʻzbekiston qonunchiligiga muvofiq verifikatsiyalangan ochiq xarita',
    descRu: 'Интерактивная карта OpenStreetMap с меткой кампуса',
    category: 'nav',
    defaultConfig: {
      titleUz: 'Texnikum joylashuvi',
      titleRu: 'Расположение техникума',
      latitude: 40.3864,
      longitude: 71.7864,
      zoom: 16,
      addressUz: 'Fargʻona shahri, B. Margʻiloniy koʻchasi, 42-uy',
      addressRu: 'г. Фергана, ул. Б. Маргилоний, 42',
      height: 360,
    },
  },
  {
    type: 'contact_card',
    icon: MapPin,
    nameUz: 'Aloqa kartasi',
    nameRu: 'Контактная карточка',
    descUz: 'Manzil, telefon raqami, elektron pochta va qabul vaqtlari',
    descRu: 'Карточка с адресом, телефонами, почтой и часами приема',
    category: 'nav',
    defaultConfig: {
      titleUz: 'Bosh korpus',
      titleRu: 'Главный корпус',
      addressUz: 'Fargʻona shahri, B. Margʻiloniy koʻchasi, 42-uy',
      addressRu: 'г. Фергана, ул. Б. Маргилоний, 42',
      phone: '+998 (73) 244-00-00',
      email: 'info@texnikum2.uz',
      workHoursUz: 'Dush–Shanba: 08:30 – 17:30',
      workHoursRu: 'Пн–Сб: 08:30 – 17:30',
    },
  },
  {
    type: 'button',
    icon: Link2,
    nameUz: 'Tugma / Havola',
    nameRu: 'Кнопка-ссылка',
    descUz: 'Alohida tugma yoki havola (asosiy, kontur, shaffof)',
    descRu: 'Кнопка для перехода на страницу или внешний сервис',
    category: 'nav',
    defaultConfig: {
      textUz: 'Batafsil maʼlumot olish',
      textRu: 'Узнать больше',
      url: '/info',
      variant: 'primary',
      align: 'left',
    },
  },
  {
    type: 'divider',
    icon: Minus,
    nameUz: 'Ajratgich chiziq',
    nameRu: 'Разделитель',
    descUz: 'Bloklar orasidagi ajratuvchi chiziq va vertikal oraliq',
    descRu: 'Визуальная разделительная линия и отступ между блоками',
    category: 'nav',
    defaultConfig: { style: 'solid', spacing: 'medium' },
  },
];
